# Week 2 Practical Session


# Software Installation

https://istd.sutd.edu.sg/50-035/installation/

* Install Anaconda

* Install OpenCV & Tensorflow

* Test your installation

Python 3 tested, not sure about Python 2 but you can try


# IPython notebook
Once your notebook server is running, point your web browser at http://localhost: to start using your notebooks.

An IPython notebook is made up of a number of cells. Each cell can contain Python code. You can execute a cell by clicking on it and pressing Shift-Enter. When you do so, the code in the cell will run, and the output of the cell will be displayed beneath the cell.


In [1]:
x = 1+1
print(x)

2


Global variables are shared between cells. 

In [2]:
y = x + 1
print(y)

3


Remember to save your changes.

# Lab Submission!
Files that end with .ipynb – run on jupyter notebook.

There are # *****TO DO/# *****END OF YOUR CODE tags denoting the start and end of code sections you should fill out. Take care to not delete or modify these tags, or your assignment may not be properly graded.


In [5]:
## example 
import cv2
img = cv2.imread('imgs/opencv_logo1.png', 1)
res = cv2.resize(img,None,fx=2.0, fy=2.0, interpolation = cv2.INTER_CUBIC)
#OR
height, width = img.shape[:2]
res = cv2.resize(img,(2*width, 2*height), interpolation = cv2.INTER_CUBIC)

################################################################################
# TO DO: Check the size of 'img' and 'res'?
################################################################################
# passs
################################################################################
#                                 END OF YOUR CODE                             #
################################################################################

################################################################################
# TO DO: Resize 'img' so as to the smaller side is 500, while keeping image 
# ration unchanged.
################################################################################
pass
################################################################################
#                                 END OF YOUR CODE                             #
################################################################################

**Homework late penalty: 50% for late submission and 0% if more than 1 week after due date.**

We use eDimension for homework.

# Speeding-up code with NumPy

NumPy is designed to help us get best of both worlds 
* Fast development time of Python
* Fast excutime of C/Fortran

... by pushing repeated operations in a statically-typed compiled layer.

Four Strategies:
1. Use NumPy's ufuncs
2. Use NumPy's aggregations
3. Use NumPy's broadcasting
4. Use NumPy's slicing, masking, and fancy indexing

## 1. Use NumPy's ufuncs
They operate element-wise on arrays.
There are many ufuncs available:
- Arithmetic operators: + - * / // % **
- Bitwise operators: & | ~ ^ >> <<
- Comparion operators: < > <= >= == !=
- Exponential faminly: np.exp, np.log ...

In [6]:
a = [1,2,3,46,24]
b = [val +5 for val in a]
print(b)

[6, 7, 8, 51, 29]


In [7]:
import numpy as np
a = np.array(a)
b = a + 5
print(b)

[ 6  7  8 51 29]


In [8]:
 a = list(range(10000))
    
%timeit [val +5 for val in a]

492 µs ± 7.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
a = np.array (a)
%timeit a+5

4.99 µs ± 121 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## 2. Use NumPy's aggregations
Aggregations are functions which summarize the values in an array (e.g min, max, sum, mean, etc)


In [10]:
from random import random

c = [random() for i in range(10000)]
%timeit min(c)

151 µs ± 4.91 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [11]:
c = np.array (c)
%timeit c.min()

4.81 µs ± 145 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## 3. Use NumPy's broadcasting
Broadcasting is a set of rules by which ufuncs operate on arrays of different sizes and/or dimensions.

In [12]:
print(np.arange(3))

[0 1 2]


In [13]:
print(np.arange(3)+5)


[5 6 7]


In [10]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
print(np.ones((3,3))+np.arange(3))

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


## 4. Use NumPy's slicing, masking, and fancy indexing


In [11]:
L = [3,4,75,2,66]
L= np.array(L)
print(L)


[ 3  4 75  2 66]


In [12]:
print(L[0])

3


In [13]:
print(L[1:3])

[ 4 75]


In [14]:
mask = np.array([False, True, True, False, True])
print(L[mask])

[ 4 75 66]


In [15]:
M = np.arange(6).reshape(2,3)
print(M)

[[0 1 2]
 [3 4 5]]


In [16]:
# multiple indices separated by comma
print(M[0,1])

1


In [17]:
#mixing slices and indices
print(M[:,1])

[1 4]


In [19]:
# mixing fancy indexing and slicing
print(M[[1,0],:2])

[[3 4]
 [0 1]]


In [18]:
# mixing masking and slicing
print(M[M.sum(axis=1)>4,1:])

[[4 5]]
